version: '3'
services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NIX_PATH=/nix/var/nix/profiles/per-user/root/channels

  metrics:
    build:
      context: .
      dockerfile: apps/metrics/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - NIX_PATH=/nix/var/nix/profiles/per-user/root/channels

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    environment:
      - NIX_PATH=/nix/var/nix/profiles/per-user/root/channels